### PR TITLE
Updated partner logos 

### PR DESCRIPTION
**Pull request by v4ltages**
Logos have been updated with much higher quality ones.
Older images/logos that are not used have been removed for spring cleaning time.

image

The questionable one is the tehnopoll logo but lets ignore that.  (Size increase)

### CODE REVIEW

**Comment by v4ltages** [comment]
Addresses issue https://github.com/Lapikud/lapikud.github.io/issues/53

**Comment by siinus** [comment]
wait...

**Comment by v4ltages** [comment]
If no changes or feedback is given in a few days. I'll consider closing this pull request completely. 😺

**Comment by v4ltages** [comment]
I'll be closing this as per https://github.com/Lapikud/lapikud.github.io/pull/98#issuecomment-2042011426 for lack of feedback or changes.

**Pull request closed without merging**
